### ISSUE TITLE
Lazy compiling

### ISSUE THREAD

**Issue by KommuSoft** [JDevlieghere/InTeXration#1]
You state the server will compile every commit. Won't this cause much overhead since most people make commits all the time (for instance they see a typo after a few seconds).

An alternative could be to do lazy compiling. You run a server and when somebody wants to generate a pdf, for instance you query the server with a url containing the sha of the commit. The server reacts by sending a PDF. You can for instance use the flyweight pattern to avoid compiling the same commit a second time.

**Comment by JDevlieghere** [comment]
I did consider lazy compiling initially but considering the time it takes to download the compiled PDF, I wasn't sure whether the additional loading time for the first view was justified by the decrease in server load. 

Currently the repository is cloned and compiled on each commit. Both operations take a considerable amount of time. One improvement that I'm thinking about is pulling rather than cloning the whole repository. However, if the server is handling a large amount of repositories, this won't be worth the disk space. 

What's your opinion on this? Is the decrease in server load worth the delay?

**Comment by KommuSoft** [comment]
Perhaps servers can compile the head of each branch/only the master branch when new commits are pushed to the repository (most users are only interested in the heads). If a user wants to compile another commit, the delay can be reasonable.

An idea might be to consider a certain quota: a certain amount of space is reserved for the application. When the repositories together exceed the quota, one or more repositories (preferably the ones that were consulted long ago) are removed (and cloned when a user queries for a pdf).

**Comment by stefanpante** [comment]
Wouldn't it also be possible to store the identifier of the commit which was the base for the compilation alongside the pdf. When a user request the pdf, the server could check if it's version number is still valid, if it's not the case, It clones the repository, compiles the tex and presents the user with the recompiled version and updates the version number.

The update of the pdf is initiated by the user in this case, rather than  on each commit.
 **Edit:** This solution is probably the same as Kommusoft suggested :p. Missed the part about the flyweight pattern.

**"I did consider lazy compiling initially but considering the time it takes to download the compiled PDF, I wasn't sure whether the additional loading time for the first view was justified by the decrease in server load."**

You could also make the user aware of the the additional load time by  displaying a page with shows when  the pdf is compiling. When the compilation is complete, you could redirect the user to the newly compiled pdf.  This way, the user knows he has to wait for the pdf

**OR**  you could give even more control to the user, If the pdf is behind, you could ask the user if he wants to view the current pdf or recompile it to a more recent version, when he selects he wants to view the current pdf, you could send it to him, recompile in the background and remove the older version when the file has transferred to the user. He will be presented with the newest version the next time he wishes to view the pdf.

**Comment by JDevlieghere** [comment]
I implemented the option to specify what branch to compile and whether to do it in a lazy manner or not.
